# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dlogdet <- function(arg, lambda) {
    .Call(`_LMMsolver_dlogdet`, arg, lambda)
}

construct_ADchol_Rcpp <- function(U, P_list) {
    .Call(`_LMMsolver_construct_ADchol_Rcpp`, U, P_list)
}

logdet <- function(arg, lambda) {
    .Call(`_LMMsolver_logdet`, arg, lambda)
}

construct_ADchol_Rcpp_NgPeyton <- function(U, P_list) {
    .Call(`_LMMsolver_construct_ADchol_Rcpp_NgPeyton`, U, P_list)
}

logdetNgPeyton <- function(arg, lambda) {
    .Call(`_LMMsolver_logdetNgPeyton`, arg, lambda)
}

dlogdetNgPeyton <- function(arg, lambda) {
    .Call(`_LMMsolver_dlogdetNgPeyton`, arg, lambda)
}

TestList <- function() {
    .Call(`_LMMsolver_TestList`)
}

