# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logdet <- function(arg, lambda) {
    .Call(`_LMMsolver_logdet`, arg, lambda)
}

dlogdet <- function(arg, lambda) {
    .Call(`_LMMsolver_dlogdet`, arg, lambda)
}

construct_ADchol_Rcpp <- function(U, P_list) {
    .Call(`_LMMsolver_construct_ADchol_Rcpp`, U, P_list)
}

